name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Deploy Static Files Directly 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # Just deploy the public folder as-is
          branch: gh-pages
